import React, { useState } from 'react';
import { CheckCircle2, RefreshCw, TrendingUp, Upload, X } from 'lucide-react';
import { apiClient } from '../../api/client';

export const AdminTrendsView: React.FC = () => {
  const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('');
  const publish=async(e:React.FormEvent)=>{e.preventDefault();if(!file)return setMsg('Choose an image.');setBusy(true);setMsg('');const data=await new Promise<string>((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result||''));fr.onerror=reject;fr.readAsDataURL(file)});const r=await apiClient.post({title,description,fileName:file.name,mimeType:file.type,fileData:data},{action:'adminUploadTrend'},{authenticated:true});setBusy(false);if(r.success){setTitle('');setDescription('');setFile(null);setMsg('Trend published successfully.')}else setMsg(r.error?.message||'Could not publish trend.')};
  return <div className="space-y-5"><div className="p-5 rounded-3xl bg-[#111712] border border-white/10"><div className="flex items-center gap-3"><TrendingUp className="text-emerald-400"/><div><h2 className="text-lg font-black text-white">Campus Trends</h2><p className="text-xs text-gray-400">Admin-only image + description posts shown in the Community Trends section.</p></div></div></div><form onSubmit={publish} className="p-5 rounded-3xl bg-[#111712] border border-white/10 grid gap-4"><input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="Trend title" className="px-4 py-3 rounded-xl bg-black/30 border border-white/10 text-white"/><textarea value={description} onChange={e=>setDescription(e.target.value)} required placeholder="Description" className="px-4 py-3 rounded-xl bg-black/30 border border-white/10 text-white min-h-28"/><label className="px-4 py-3 rounded-xl border border-dashed border-white/15 text-gray-400 text-sm cursor-pointer"><Upload className="inline w-4 h-4 mr-2"/> {file?.name||'Choose trend image'}<input hidden type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{msg&&<div className="text-xs text-emerald-300 flex items-center gap-2"><CheckCircle2 className="w-4 h-4"/>{msg}</div>}<button disabled={busy} className="px-4 py-3 rounded-xl bg-emerald-500 text-black font-black text-sm">{busy?'Publishing…':'Publish trend'}</button></form></div>;
};
